spring.application.name=role-api

spring.datasource.url= jdbc:postgresql://ep-snowy-dust-acyyq3ee-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_pDNVbefjB3C0&sslmode=require&channelBinding=require
spring.datasource.username=ep-snowy-dust-acyyq3ee-pooler
spring.datasource.password=pg_pDNVbefjB3C0&

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect